### ISSUE TITLE
nullmailer removes ssmtp

### ISSUE THREAD

**Issue by lejmr** [florianutz/ubuntu2004_cis#12]
**Describe the bug**
Turns out nullmailer is the only mailer considered by the role. Problem is this role doesn't provide a way how to configure it. I am ending up with a machine unable to send emails out.

**To Reproduce**
1. Remove postfix
2. Configure ssmtp
3. start this role against the server

**Expected behavior**
I am expecting role leaves ssmtp being configured on the system as it is, or role provides a way how to configure nullmailer.

**Software (please complete the following information):**
 - Ansible Version: [e.g. 2.9.0]
 - Role/Repo Version [e.g. 1.0.0, master]

**Comment by lejmr** [comment]
will try to make a pull-request to fix it.. doesn't seem the nullmailer is required by CIS itself.

**Comment by florianutz** [comment]
@lejmr you are right. The package is only installed because auditd otherwise install postfix. It requires an local mta. If you have an idea how we can check if a mta is already installed I would be happy about your contribution.
