### ISSUE TITLE
Breaks sudo.

### ISSUE THREAD

**Issue by devatnull** [florianutz/ubuntu2004_cis#14]
When run like this:

```
sudo apt-get install -y ansible
sudo sh -c "echo '- src: https://github.com/florianutz/ubuntu2004_cis' >> /etc/ansible/requirements.yml"
cd /etc/ansible/
sudo ansible-galaxy install -p roles -r /etc/ansible/requirements.yml

sudo sh -c "cat > /etc/ansible/harden.yml <<EOF
- name: Harden Server
  hosts: localhost
  connection: local
  become: yes
  roles:
    - ubuntu2004_cis
EOF
"
sudo ansible-playbook /etc/ansible/harden.yml

sudo apt-get install cracklib-runtime -y
```

It breaks sudo. 
In order to confirm:
1- install fresh ubuntu 20.04
2- give your user a password, any password.
3- add your user to sudo group
4- run the script above
5- test "sudo su"
6- reboot the machine
7- test "sudo su" now

**Comment by florianutz** [comment]
I think this is a feature and not a bug. Check 5.3.2
You can easily check the status of your failed logon count by executing `pam_tally2` as root
This keeps bad guys out of Grayskull.

**Comment by devatnull** [comment]
I am not a bad guy. I enter the correct password that I set, su to another user, you can "sudo su" fine, but on the first user created this will appear.

**Comment by florianutz** [comment]
I did not say that you are a bad guy. But maybe you use a bad ssh client configuration which attempt to use e.g. password before pubkey. Or some other service which will generate a failed logon. Just ssh into your machine. If sudo not works wait for 15 minutes (Timeout set in ansible role) and try it again.

**Comment by florianutz** [comment]
@devatnull any updates on this?

**Comment by devatnull** [comment]
Yes, you are right, you have to wait 15 minutes. Password auth on my server is closed only pubkey, same behavior from terminal and termius ssh client. But in my opinion there should be an indicator about this in the readme. Thanks for your time, we can close the issue.

**Comment by florianutz** [comment]
this error occurs occasionally. sometimes people have stored several ssh keys on there client. the ssh client then tries all keys and generates an incorrect login with each incorrect key.

**Comment by florianutz** [comment]
@devatnull I came across the following link https://access.redhat.com/solutions/29233 . Are you able to verify if disabling ChallengeResponseAuthentication solve the problem?
