### ISSUE TITLE
2.2.1.3 | PATCH | Ensure chrony is configured -> Failed

### ISSUE THREAD

**Issue by munish07** [florianutz/ubuntu2004_cis#27]
**Describe the bug**
2.2.1.3 | PATCH | Ensure chrony is configured -> Failed 

As per the documentation, /etc/chrony/chrony.conf should be updated to add a line "user _chrony". 
The ansible playbook is not doing that. Editing the file manually and adding that file solves the failures. 
Ansible playbook should be updated to fix that. 

**Expected behavior**
2.2.1.3 should Pass

**Software (please complete the following information):**
 - Ansible Version: 2.9

**Additional context**

**Comment by kdebisschop** [comment]
Related to this, I think...

/etc/sysconfig/chronyd inserts a line "OPTIONS=\"-u chrony\"" -- but on ubuntu 18 and 20, the user is "_chrony"

Easy to patch -- not sure if it is just a typo or should be configurable.

I'm going to make a PR for "SCORED | 2.2.1.3 | PATCH | Ensure chrony is configured | modify /etc/sysconfig/chronyd" assuming it should be configurable.

**Comment by florianutz** [comment]
Closed by #39
