### ISSUE TITLE
cis for ubuntu 22.04

### ISSUE THREAD

**Issue by rabiayilmazz** [florianutz/ubuntu2004_cis#49]
can we use this repo for ubuntu 22.04? Or will you write new cis for ubuntu 22.04?

**Comment by florianutz** [comment]
Currently there are no dedicated cis benchmarks for 22.04. As soon as these appear there will be a new version for 22.04. This role for 20.04 should work with 22.04 though. In any case, try them first on a test system!

**Comment by rabiayilmazz** [comment]
OK thanks. I'm calling it. it works but we need to create ansible directory. Other than that, I didn't see any problems.
