### ISSUE TITLE
Ubuntu 2004 support

### ISSUE THREAD

**Issue by liuyangc3** [florianutz/ubuntu2004_cis#9]
Hi is there any plan to support Ubuntu 20.04?

**Comment by florianutz** [comment]
Issue transfered to 2004 repository.
Tagged first release 1.0.0 based on @a7i contributions.

**Comment by liuyangc3** [comment]
Thanks I will try this on AWS later

**Comment by florianutz** [comment]
@liuyangc3 any updates about this?

**Comment by DB-Vincent** [comment]
I've just ran it on a test machine and tested it with Wazuh, the score went from 33% to 84%. A lot more secure, but there are a few things he's still marking as failed. For example, he's telling me there are some options missing on some directories.
![Wazuh_CIS](https://user-images.githubusercontent.com/48948316/100084867-9b6d7980-2e4b-11eb-8f32-deea99e1fba9.jpg)

**Comment by florianutz** [comment]
@DB-Vincent thanks a lot for testing. Unfortunately, some of the items are difficult to implement as a generic ansible role. Mount options are one of them. Especially cloud images often have only one partition.

**Comment by DB-Vincent** [comment]
@florianutz I've been trying out a few things inside the playbook in order to try to fix those items. The main problem is that ansible keeps skipping the tasks on my machine (although they're all enabled).
